In [9]:
import pandas as pd

student = pd.read_csv("110_student.csv")


student_male = list(student['男生計'])
student_all = list(student['總計'])

student

,學校代碼,學校名稱,日間∕進修別,等級別,總計,男生計,女生計,一年級男生,一年級女生,二年級男生,...,五年級男生,五年級女生,六年級男生,六年級女生,七年級男生,七年級女生,延修生男生,延修生女生,縣市名稱,體系別
0,1,國立政治大學,D 日,D 博士,948,537,411,88,67,81,...,71,57,71,40,61,52,-,-,30 臺北市,1 一般
1,1,國立政治大學,D 日,M 碩士,"3,974","1,828","2,146",624,729,591,...,3,-,-,-,-,-,-,-,30 臺北市,1 一般
2,1,國立政治大學,D 日,B 學士,"9,556","3,920","5,636",900,"1,303",920,...,-,-,-,-,-,-,289,423,30 臺北市,1 一般
3,1,國立政治大學,N 職,M 碩士,"1,632",779,853,227,294,239,...,72,65,1,-,-,-,-,-,30 臺北市,1 一般
4,2,國立清華大學,D 日,D 博士,"1,663","1,192",471,248,114,193,...,112,47,95,31,165,54,-,-,18 新竹市,1 一般
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
786,1293,崇仁醫護管理專科學校,D 日,5 五專,"3,209",445,"2,764",110,519,95,...,81,559,-,-,-,-,11,46,10 嘉義縣,2 技職
787,3002,臺北市立大學,D 日,D 博士,220,95,125,16,18,13,...,10,13,9,10,20,36,-,-,30 臺北市,1 一般
788,3002,臺北市立大學,D 日,M 碩士,"1,348",447,901,144,292,125,...,19,65,17,33,-,-,-,-,30 臺北市,1 一般
789,3002,臺北市立大學,D 日,B 學士,"5,345","2,363","2,982",575,727,552,...,-,-,-,-,-,-,188,111,30 臺北市,1 一般
790,3002,臺北市立大學,N 職,M 碩士,"1,201",316,885,105,280,96,...,19,54,22,50,-,-,-,-,30 臺北市,1 一般

In [10]:
# 差集

set_all = set(student_all)
set_male = set(student_male)

{'1,007',
 '1,010',
 '1,012',
 '1,018',
 '1,042',
 '1,048',
 '1,062',
 '1,063',
 '1,072',
 '1,083',
 '1,090',
 '1,094',
 '1,114',
 '1,115',
 '1,122',
 '1,146',
 '1,168',
 '1,196',
 '1,197',
 '1,201',
 '1,209',
 '1,259',
 '1,277',
 '1,278',
 '1,289',
 '1,300',
 '1,317',
 '1,320',
 '1,324',
 '1,346',
 '1,348',
 '1,358',
 '1,366',
 '1,387',
 '1,390',
 '1,404',
 '1,415',
 '1,418',
 '1,428',
 '1,433',
 '1,438',
 '1,442',
 '1,454',
 '1,461',
 '1,475',
 '1,492',
 '1,502',
 '1,518',
 '1,528',
 '1,537',
 '1,544',
 '1,556',
 '1,558',
 '1,573',
 '1,582',
 '1,597',
 '1,604',
 '1,612',
 '1,630',
 '1,631',
 '1,632',
 '1,637',
 '1,640',
 '1,643',
 '1,647',
 '1,655',
 '1,663',
 '1,682',
 '1,695',
 '1,698',
 '1,704',
 '1,706',
 '1,728',
 '1,746',
 '1,781',
 '1,787',
 '1,790',
 '1,804',
 '1,808',
 '1,822',
 '1,827',
 '1,872',
 '1,887',
 '1,923',
 '1,932',
 '1,955',
 '1,969',
 '1,987',
 '10,582',
 '10,720',
 '101',
 '11,138',
 '11,467',
 '11,758',
 '11,851',
 '113',
 '115',
 '116',
 '119',
 '12,061',
 '12,285',
 '121',
 '122',
 '123',
 '128',
 '13,147',
 '13,658',
 '130',
 '132',
 '134',
 '143',
 '144',
 '148',
 '150',
 '154',
 '155',
 '16,906',
 '161',
 '164',
 '168',
 '169',
 '17,321',
 '17,355',
 '17,453',
 '17,751',
 '173',
 '193',
 '198',
 '199',
 '2,010',
 '2,069',
 '2,071',
 '2,134',
 '2,179',
 '2,200',
 '2,213',
 '2,237',
 '2,273',
 '2,346',
 '2,353',
 '2,384',
 '2,438',
 '2,461',
 '2,474',
 '2,530',
 '2,583',
 '2,637',
 '2,651',
 '2,653',
 '2,682',
 '2,798',
 '2,821',
 '2,833',
 '2,837',
 '2,838',
 '2,844',
 '20,203',
 '20,763',
 '202',
 '203',
 '205',
 '216',
 '230',
 '235',
 '243',
 '246',
 '249',
 '253',
 '256',
 '261',
 '265',
 '266',
 '274',
 '276',
 '280',
 '283',
 '286',
 '291',
 '294',
 '297',
 '299',
 '3,005',
 '3,033',
 '3,036',
 '3,040',
 '3,074',
 '3,110',
 '3,147',
 '3,170',
 '3,177',
 '3,180',
 '3,190',
 '3,193',
 '3,209',
 '3,234',
 '3,318',
 '3,477',
 '3,501',
 '3,504',
 '3,525',
 '3,535',
 '3,550',
 '3,564',
 '3,620',
 '3,625',
 '3,648',
 '3,666',
 '3,679',
 '3,690',
 '3,703',
 '3,738',
 '3,793',
 '3,841',
 '3,848',
 '3,852',
 '3,870',
 '3,892',
 '3,938',
 '3,955',
 '3,974',
 '305',
 '306',
 '311',
 '312',
 '314',
 '319',
 '322',
 '325',
 '342',
 '355',
 '360',
 '364',
 '370',
 '374',
 '383',
 '389',
 '392',
 '395',
 '399',
 '4,050',
 '4,063',
 '4,113',
 '4,199',
 '4,272',
 '4,344',
 '4,359',
 '4,476',
 '4,534',
 '4,551',
 '4,606',
 '4,646',
 '4,799',
 '4,804',
 '4,829',
 '4,861',
 '4,942',
 '404',
 '408',
 '415',
 '416',
 '417',
 '423',
 '429',
 '430',
 '434',
 '439',
 '444',
 '449',
 '452',
 '458',
 '459',
 '480',
 '493',
 '5,236',
 '5,247',
 '5,345',
 '5,424',
 '5,570',
 '5,583',
 '5,638',
 '5,751',
 '5,793',
 '5,899',
 '5,956',
 '5,970',
 '5,985',
 '500',
 '505',
 '516',
 '521',
 '532',
 '538',
 '539',
 '546',
 '548',
 '549',
 '550',
 '552',
 '554',
 '558',
 '559',
 '562',
 '563',
 '575',
 '581',
 '582',
 '588',
 '590',
 '592',
 '595',
 '6,055',
 '6,058',
 '6,068',
 '6,072',
 '6,104',
 '6,236',
 '6,254',
 '6,287',
 '6,414',
 '6,435',
 '6,565',
 '6,585',
 '6,630',
 '6,743',
 '6,756',
 '6,812',
 '6,813',
 '618',
 '621',
 '625',
 '632',
 '644',
 '645',
 '647',
 '652',
 '654',
 '656',
 '662',
 '668',
 '679',
 '691',
 '696',
 '7,072',
 '7,106',
 '7,165',
 '7,205',
 '7,224',
 '7,239',
 '7,340',
 '7,383',
 '7,516',
 '7,547',
 '7,618',
 '7,640',
 '7,673',
 '7,847',
 '706',
 '720',
 '723',
 '724',
 '725',
 '726',
 '727',
 '739',
 '744',
 '75',
 '753',
 '754',
 '755',
 '757',
 '765',
 '768',
 '770',
 '771',
 '774',
 '776',
 '781',
 '783',
 '798',
 '8,069',
 '8,313',
 '8,431',
 '8,630',
 '8,888',
 '804',
 '808',
 '829',
 '836',
 '84',
 '853',
 '859',
 '869',
 '877',
 '882',
 '886',
 '9,010',
 '9,443',
 '9,517',
 '9,556',
 '903',
 '906',
 '907',
 '910',
 '912',
 '927',
 '929',
 '93',
 '933',
 '936',
 '948',
 '950',
 '954',
 '988',
 '99'}